# SPDX-License-Identifier: Apache-2.0
# K9-AIF Framework
"""The guidelines document generated for each inspection.

Deterministic: built from the report and the rules' own descriptions and fixes
(no model call), so the same code always yields the same document. It turns
the findings into a remediation plan ordered by severity, explains why each
rule exists in the framework, and gives the framework settings that close the
governance findings.
"""

from __future__ import annotations

from collections import OrderedDict
from typing import Any, Dict, List

from k9_aif_abb.k9_inspect import InspectionRuleRegistry

_SEV = ["critical", "violation", "warning", "recommendation"]
_WHEN = {"critical": "Now — before the next deployment", "violation": "Before production",
         "warning": "Next iteration", "recommendation": "When the code is next touched"}

_GOVERNANCE_SNIPPET = """```yaml
# config/config.yaml — every agent is then governed by construction (k9-aif >= 1.15)
governance:
  guardian:
    enabled: true
    model: granite4.1-guardian:8b
    on_unavailable: fail_closed
security:
  shield:
    enabled: true
    strict: false
    ingress:
      checks: [InputSizeCheck, PromptInjectionCheck, PIIBoundaryCheck, PIIRequestCheck]
    egress:
      checks: [PIIBoundaryCheck, OutboundLinkCheck, SystemPromptLeakageCheck]
    check_config:
      OutboundLinkCheck: {allowed_domains: [your-company.com]}
```"""

_ZERO_TRUST_SNIPPET = """```yaml
# Zero Trust at the orchestrator: identity from a signed stamp, not from the payload
enable_zero_trust: true
security:
  identity: {mode: signed}          # K9_IDENTITY_SECRET in .env, same on Router and Orchestrators
  auth:
    providers:                      # or type: oidc / keycloak / entra_id / okta
      - type: api_key
        api_keys:
          claims-bot: {env: K9_KEY_CLAIMS_BOT, principal_type: agent, roles: [claims_approver]}
```"""


def rule_catalog() -> Dict[str, Dict[str, str]]:
    return {r.rule_id: r().describe() for r in InspectionRuleRegistry.all()}


def build(report: Dict[str, Any], app_name: str = "") -> str:
    rules = rule_catalog()
    findings: List[Dict[str, Any]] = report["findings"]
    c = report["counts"]
    title = app_name or report["source"]
    lines = [
        f"# Conformance guidelines — {title}", "",
        f"Generated by K9X Inspector from the inspection of `{report['source']}`"
        + (f" at commit `{report['commit'][:12]}`" if report.get("commit") else "")
        + f" (k9-aif {report['framework_version']}, {report['inspected_at']}).", "",
        "## Where the solution stands", "",
        f"**{report['verdict']}** — {report['score']}% of {len(report['rules'])} rules pass. "
        f"{c['critical']} critical, {c['violation']} violations, {c['warning']} warnings, "
        f"{c['recommendation']} recommendations.", "",
    ]
    if not findings:
        lines += ["No findings: the solution follows every rule this inspection applies. Keep it that way by "
                  "running `k9aif inspect <folder> --fail-on violation` in CI.", ""]
    else:
        lines += ["## Remediation plan", "",
                  "Work top to bottom. Each item names the rule, why the framework has it, where it is "
                  "violated and how to fix it.", ""]
        by_rule: "OrderedDict[str, List[Dict[str, Any]]]" = OrderedDict()
        for f in sorted(findings, key=lambda f: (_SEV.index(f["severity"]), f["rule_id"])):
            by_rule.setdefault(f["rule_id"], []).append(f)
        step = 0
        for sev in _SEV:
            group = [(rid, fs) for rid, fs in by_rule.items() if fs[0]["severity"] == sev]
            if not group:
                continue
            lines += [f"### {sev.capitalize()} — {_WHEN[sev]}", ""]
            for rid, fs in group:
                step += 1
                r = rules.get(rid, {})
                lines += [f"**{step}. {r.get('title', rid)}** (`{rid}`, {len(fs)} place{'s' if len(fs) > 1 else ''})", ""]
                if r.get("description"):
                    lines += [f"*Why:* {r['description']}", ""]
                for f in fs[:25]:
                    where = f"`{f['file']}:{f['line']}`" if f.get("line") else (f"`{f['file']}`" if f.get("file") else "solution")
                    lines.append(f"- {where} — {f['message']}")
                if len(fs) > 25:
                    lines.append(f"- … and {len(fs) - 25} more (see the full report)")
                lines += ["", f"*Fix:* {fs[0].get('fix') or r.get('fix', '')}", ""]
    gov_ids = {f["rule_id"] for f in findings if f["category"] == "Governance"}
    if gov_ids:
        lines += ["## Governance configuration", "",
                  "Since k9-aif 1.15 governance is a configuration of the solution, not code in each agent: "
                  "with Shield enabled, every agent's execute() and every llm_invoke() call outside an agent is "
                  "checked, and production refuses to run without it. A starting configuration:", "",
                  _GOVERNANCE_SNIPPET, ""]
    lines += ["## Framework practices this inspection enforces", "",
              "- **ABB/SBB separation.** Agents, squads, orchestrators and routers extend the framework's ABB "
              "contracts; domain logic lives in the SBB and nowhere else.",
              "- **Three-layer decoupling.** Router → Orchestrators → Squads → Agents; each layer knows only "
              "the one below. Agent registration happens in the entry point.",
              "- **One model path.** Every model call goes through `llm_invoke()` — governance, retries on empty "
              "replies and the LLMCall trace all live there.",
              "- **Kafka ownership.** Only Routers and Orchestrators publish; agents raise `RequiresHIL` to ask "
              "for a human decision.",
              "- **Secrets in the environment.** `.env` is gitignored; YAML holds `${VAR}` references only.",
              "- **Zero Trust at the orchestrator** for identity, authorization and data-loss controls:", "",
              _ZERO_TRUST_SNIPPET, "",
              "## Keep it compliant", "",
              "- CI: `k9aif inspect <folder> --fail-on violation` (exit 1 on a violation).",
              "- K9X Inspector re-inspects this application on every push (GitHub webhook) or on its schedule.",
              ""]
    return "\n".join(lines)
